### ISSUE TITLE
no module named packaging

### ISSUE THREAD

**Issue by sirus20x6** [NousResearch/finetuning-subnet#18]
this is in a fresh conda. installing the packaging package with pip doesn't help

```
Obtaining file:///code/git/finetuning-subnet
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting bittensor==6.9.3 (from finetuning-subnet==0.2.4)
  Using cached bittensor-6.9.3-py3-none-any.whl.metadata (20 kB)
Collecting huggingface-hub (from finetuning-subnet==0.2.4)
  Using cached huggingface_hub-0.22.2-py3-none-any.whl.metadata (12 kB)
Collecting matplotlib (from finetuning-subnet==0.2.4)
  Using cached matplotlib-3.8.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.8 kB)
Collecting numpy (from finetuning-subnet==0.2.4)
  Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting pandas (from finetuning-subnet==0.2.4)
  Using cached pandas-2.2.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Collecting pydantic==1.10 (from finetuning-subnet==0.2.4)
  Using cached pydantic-1.10.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (138 kB)
Collecting python-dotenv (from finetuning-subnet==0.2.4)
  Using cached python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Collecting rich (from finetuning-subnet==0.2.4)
  Using cached rich-13.7.1-py3-none-any.whl.metadata (18 kB)
Collecting safetensors (from finetuning-subnet==0.2.4)
  Using cached safetensors-0.4.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting torch (from finetuning-subnet==0.2.4)
  Using cached torch-2.2.2-cp311-cp311-manylinux1_x86_64.whl.metadata (25 kB)
Collecting transformers==4.38.2 (from finetuning-subnet==0.2.4)
  Using cached transformers-4.38.2-py3-none-any.whl.metadata (130 kB)
Collecting wandb (from finetuning-subnet==0.2.4)
  Using cached wandb-0.16.6-py3-none-any.whl.metadata (10 kB)
Collecting sentencepiece (from finetuning-subnet==0.2.4)
  Using cached sentencepiece-0.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.7 kB)
Collecting jinja2>=3.0.0 (from finetuning-subnet==0.2.4)
  Using cached Jinja2-3.1.3-py3-none-any.whl.metadata (3.3 kB)
Collecting flash-attn==2.5.5 (from finetuning-subnet==0.2.4)
  Using cached flash_attn-2.5.5.tar.gz (2.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/code/git/finetuning-subnet/subnet/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/code/git/finetuning-subnet/subnet/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/code/git/finetuning-subnet/subnet/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ck9af66h/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ck9af66h/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-ck9af66h/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-ck9af66h/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 9, in <module>
      ModuleNotFoundError: No module named 'packaging'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by vominh1919** [comment]
Opened PR #32 to fix this: https://github.com/NousResearch/finetuning-subnet/pull/32
